### ISSUE TITLE
tried to install examples on windows 10 and got the following:

### ISSUE THREAD

**Issue by srconklin** [foxdonut/meiosis-examples#1]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\scott\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! meiosis-examples@0.7.0 prestart: `npm i && npm run examples`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meiosis-examples@0.7.0 prestart script 'npm i && npm run examples'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meiosis-examples package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && npm run examples
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meiosis-examples
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meiosis-examples
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\inetpub\wwwroot\meiosis-examples\npm-debug.log

C:\inetpub\wwwroot\meiosis-examples>
[npm-debug.log.txt](https://github.com/foxdonut/meiosis-examples/files/392703/npm-debug.log.txt)

**Comment by srconklin** [comment]
FYI: 
I got this message also when trying to install meiosis from npm

 fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN SAMES6@1.0.0 No repository field.

**Comment by foxdonut** [comment]
@srconklin thank you for the report! I have fixed this in the `windows` branch. The `npm start` command from the `meiosis-examples` directory should now work. Can you please verify, before I merge it back to `master`?

**Comment by srconklin** [comment]
@foxdonut  that did it.. all working now. thanks!

**Comment by foxdonut** [comment]
@srconklin great to hear!
