### ISSUE TITLE
preact example and meiosis-preact package

### ISSUE THREAD

**Issue by osdevisnot** [foxdonut/meiosis-examples#2]
[Preact](https://preactjs.com/) is crazy small and ridiculously fast alternative to React only behind inferno in render perfs. When I was trying to integrate Preact with meiosis, I found that a package similar to `meiosis-inferno` or `meiosis-react` is not available yet. Any chance this can be added? 

Looking forward to see preact integration example.

**Comment by foxdonut** [comment]
@osdevisnot good point! I am currently working on a new version of Meiosis for which it will be easier to use Preact or any other virtual-dom library. Here is an [example that uses Preact](https://github.com/foxdonut/meiosis-examples/blob/master/examples/temperatures/app/index.js#L2).

**Comment by osdevisnot** [comment]
@foxdonut Thanks. That link unfortunately renders a 404 for me.

**Comment by foxdonut** [comment]
@osdevisnot sorry about that, [here is the corrected link](https://github.com/foxdonut/meiosis-examples/blob/master/examples/temperatures/src/app/index.js#L2).

**Comment by foxdonut** [comment]
[Example of using preact](https://github.com/foxdonut/meiosis-examples/blob/master/examples/temperatures/src/index.js#L2)
