### ISSUE TITLE
realworld-common/src/credentials/actions

### ISSUE THREAD

**Issue by idkjs** [foxdonut/meiosis-examples#8]
Looks like you intended to create the `realworld-common` folder but have not got to it yet. FYI.

Thanks for sharing your ideas.

**Comment by foxdonut** [comment]
@idkjs you are right, I am in the middle of re-organizing that example. Thank you! I will notify when the example is ready. I appreciate your interest.

**Comment by idkjs** [comment]
Will look out for it. I was playing with the pattern in reason-react. Almost feels like it already does this by default. Do you think the style makes sense in a compile to js functional language?

**Comment by foxdonut** [comment]
@idkjs I have finished the realworld example.
