### ISSUE TITLE
random-gif consumes so much memory

### ISSUE THREAD

**Issue by sassanh** [foxdonut/meiosis-examples#9]
I just ran memory gif example and it seems to consume lots of memory on my machine. Do you know why? I haven't read the details of meiosis yet but I'm wondering if it's related to the meiosis pattern or just a bad implementation on this particular example.

**Comment by foxdonut** [comment]
@sassanh interesting. Would you mind trying it without Meiosis Tracer and see if that makes a significant difference?

**Comment by sassanh** [comment]
I just cloned the repo and disabled the Tracer, it's still consuming a lot of ram, by pressing "Random gif" button around 20 times it reached to 1GB.
![image](https://user-images.githubusercontent.com/1270688/45747785-26bfa480-bc1c-11e8-9f68-9814e5bd98b8.png)

**Comment by sassanh** [comment]
Thanks for quick response. I'm glad you found the issue fast.

**Comment by porsager** [comment]
@foxdonut That's very interesting.. To be honest I haven't at all dived into memory yet (only cpu), so it's very likely. It's good to have a reproducible case to go from, I've created https://github.com/porsager/bss/issues/28 to track it :)
